# Generated by Django 4.0.4 on 2022-06-21 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ONB_admin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
